@startuml upgrade_menu

class scenes.UpgradeMenu extends scenes.HorizontalMenu {
	+ apply_upgrade: function

	+ UpgradeMenu(upgrades: list[MagicUpgrade], apply_upgrade: function)
	+ setup()
	- create_upgrade_card()
	- select_upgrade()
	- get_offsets()
}

scenes.UpgradeMenu o--> mechanics.MagicUpgrade : upgrades

@enduml
