@startuml levels

skinparam class {
  BackgroundColor #bee1e6
}

class scenes.Scene {
	+ load_completed: bool
	+ scene_music: systems.Resource

	+ Scene()
	+ load()
	+ setup()
	+ pop_back()
	{abstract} + update(elapsed_time: number)
	{abstract} + handle_events(events: List[pygame.Event])
	{abstract} + draw(screen: pygame.Surface)
}

class scenes.Level extends scenes.Scene {
  + magic_upgrade_system: mechanics.MagicUpgradeSystem
  + tech_upgrade_system: mechanics.TechUpgradeSystem  
}

class generation.BaseGenerator {
}

class generation.BaseTerrain {
}

class scenes.ScrollableGroup extends pygame.sprite.Group {
  + parallax_x: float
  + parallax_y: float
  + cull: bool

  + ScrollableGroup(sprites: List[pygame.sprite.Sprite])
  + draw(surface: pygame.Surface)
}

class scenes.ParallaxGroup extends scenes.ScrollableGroup {
  + ParallaxGroup(parallax: float, sprites: List[pygame.sprite.Sprite])
}

class scenes.EnemyGroup {
  + num_sprites: number

  + EnemyGroup(sprites: List[pygame.sprite.Sprite])
  + add_internal(sprite: pygame.sprite.Sprite)
  + remove_internal(sprite: pygame.sprite.Sprite)
  + empty()
  + get_num_enemies()
}

scenes.EnemyGroup -up-|> scenes.ScrollableGroup
scenes.EnemyGroup --|> utils.Observable


scenes.ScrollableGroup --> systems.CameraManager

scenes.Level "1" o--> "1" entities.Player


scenes.Level --> scenes.ScrollableGroup
scenes.Level "1" o--> "1" generation.BaseGenerator
generation.BaseTerrain "1" <--o "1" generation.BaseGenerator

@enduml
