@startuml levels

class scenes.Scene {
	+ load_completed: bool
	+ scene_music: systems.Resource

	+ Scene()
	+ load()
	+ setup()
	+ pop_back()
	{abstract} + update(elapsed_time: number)
	{abstract} + handle_events(events: List[pygame.Event])
	{abstract} + draw(screen: pygame.Surface)
}

class scenes.Level extends scenes.Scene {
  + magic_upgrade_system: mechanics.MagicUpgradeSystem
  + tech_upgrade_system: mechanics.TechUpgradeSystem  
}

class generation.BaseGenerator {
}

class generation.BaseTerrain {
}

scenes.Level "1" o--> "1" entities.Player


scenes.Level --> scenes.ScrollableGroup
scenes.Level "1" o--> "1" generation.BaseGenerator
generation.BaseTerrain "1" <--o "1" generation.BaseGenerator

@enduml
