@startuml planet


class scenes.PlanetLevel extends scenes.Level{
    + PlanetLevel()
    + update(elapsed_time: number)
    + setup()
}

class scenes.PlanetGenerator extends generation.BaseGenerator{

    + PlanetGenerator(terrain: scenes.PlanetTerrain)
    + coordinate_transform(x: number, y: number): tuple[number,number]
    + get_sprite(x: number, y: number,
        surroundings: list[tuple[number,number]]): pygame.sprite.Sprite
    + get_wall_sprite(x: number, y: number,
        surroundings: list[tuple[number,number]]): pygame.sprite.Sprite
    + get_ground_sprite(x: number, y: number): pygame.sprite.Sprite
    + noise_wall_condition(n: number, x: number, y: number): bool
    + distance_function(x0: number, y0: number, x1: number,
        y1: number, depth: number): number
}

class scenes.PlanetTerrain extends generation.BaseTerrain{

    + PlanetTerrain()
    + populate()
    + place_end(end_coords: tuple[number,number])
    + place_start_sprite(x: number, y: number)
    + place_end_sprite()
    + open_ending()
}

scenes.Level "1" o-up-> "1" generation.BaseGenerator
generation.BaseTerrain "1" --o "1" generation.BaseGenerator

@enduml